name: mlops-monitoring

services:

  api:
    build: ./fastapi-app
    container_name: mlops_api
    ports:
      - "${FASTAPI_PORT}:8000"
    volumes:
      - mlops_logs:/logs
    networks:
      - mlops_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"

  streamlit:
    build: ./streamlit-app
    container_name: mlops_streamlit
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - mlops_logs:/logs
    networks:
      - mlops_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"

  prometheus:
    image: prom/prometheus:latest
    container_name: mlops_prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - mlops_prometheus_config:/etc/prometheus/prometheus.yml
    networks:
      - mlops_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  grafana:
    image: grafana/grafana:latest
    container_name: mlops_grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - mlops_grafana_provisioning:/etc/grafana/provisioning
    networks:
      - mlops_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - mlops_network
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: "0.10"

volumes:
  mlops_logs:
    name: mlops_logs
  mlops_prometheus_config:
    name: mlops_prometheus_config
  mlops_grafana_provisioning:
    name: mlops_grafana_provisioning

networks:
  mlops_network:
    name: mlops_network